### ISSUE TITLE
Naming suggestions

### ISSUE THREAD

**Issue by grothesque** [fre-hu/mdarray#2]
Coming from C++, Python/Numpy and Rust, my impression is that some of the most central concepts of mdarray are named in a confusing way.  Perhaps this is due to my rudimentary understanding, but perhaps the author will find an outsider's perspective interesting.  Here are some of my thoughts.

### Span

In C++ there is `std::span`, but in Rust the equivalent is `slice`.  The same name is used in Python/Numpy, so many potential users have been exposed to it.  Wouldn't it be better to use the name `Slice` instead of `Span` in mdarray?  (E.g. there would be `Slice` and `RawSlice`, etc.)

But if I understand correctly, mdarray's `Span` is not really the equivalent of C++'s `mdspan`.  (That would be rather `Expr`.)  Mdarray's `Span` seems rather a simple reference to an existing array.  So how about renaming it to `ArrReference` or `ArrRef`? 

### Grid

I'm not aware of the name "grid" being used in numerical computing, except in the sense of a physical grid (e.g. a hexagonal grid), or in "grid computing".  So while short, `Grid` does not seem intuitive for "owned array".  How about renaming `Grid` to simply `Array`?  Alternatively, if ownership is to be emphasized, how about `OwnedArr`?

### Array
Static arrays in mdarray are called `Array` which nicely mirrors the usage in Rust, but arguably conflicts with the expectation that the name "Array" in an array library denotes a heap-allocated array.  How about renaming it to `StaticArr`?

### Expression

In computing, the term "expression" means "something that can be evaluated to determine its value".  If my understanding is correct, mdarray's trait `Expression` is an array iterator.  Why not call it `ArrIterator` then?  Then there could be `IntoArrIterator` etc.  This naming should be much clearer to people having some experience with Rust.

### Expr

If I understand correctly, `Expr` is an "owned view".  While `Span` is just a "reference to an array", and `Expr` has its own shape and stried.  Only the actual array values are that of another array.  So how about calling it `ArrView`?

### shorter names

Perhaps the different names proposed here are deemed a bit long.  One possibility would be to get rid of the "Arr" and simply have `Iterator`, `Ref`, `View`, `Static`, `Owned`.  If mdarray is used as `md` these would become `md::View` or `md::Iterator` which I'd say are fine.

My gut feeling is that the longer names are preferable, though.  It feels a bit presumptuous to introduce another `Iterator` trait.

**Comment by fre-hu** [comment]
Thanks. It is good to get comments, and naming is not easy and a compromise.

For Span, I agree Slice could work and is commonly used. The reason for using Span is mainly to align with C++, but it is not that important. One slight drawback with Slice is risk of confusion with normal slices, but it is the case also for Array.

Grid is maybe the most controversial, but it is being used for multidimensional arrays for example in some crates. One alternative could be Tensor, which is well known and used e.g. in C++ Eigen/xtensor and in Python. Would that work?

For Expression/Expr/... the idea is as you have seen to mirror the iterator types. But they can be seen as more than iterators, for example there are operators defined and they can be mixed with arrays. So they are not that different from expression templates in C++ libraries. I also wanted to have short names for expr/expr_mut/into_expr since they could be quite common.

**Comment by fre-hu** [comment]
One thing that causes confusion is that Expr/ExprMut are used for both array views and expressions. It is probably better to call them View/ViewMut instead. It makes it clear they are array views, and that they happen to implement Expression like some other types. To make it consistent, IntoExpr should no longer be an array type that that can be dereferenced to Span.

The existing Expr/ExprMut types could of course be kept for expressions, and that View/ViewMut implement IntoExpression instead of Expression. However I think it seems better to remove them to simplify and reduce the number of types.

Renaming Span to Slice is fine I think, as the latter is more well known. It also makes sense since it is unsized and must be used behind a reference like normal slices.

Regarding owned arrays, the Array type is just a wrapper around a normal array. It contains no pointer, so it can't be replaced with an array view. Given that there are two owned array types, it seems better to use Array for the fixed array since it is a wrapper and to make it consistent with normal arrays. I don't think it is that bad to use Tensor for a dynamic array, since it is commonly used for a multidimensional array in other libraries.

So with this my current thinking is to do these renamings:

- Grid -> Tensor
- Span -> Slice
- Expr/ExprMut -> View/ViewMut

**Comment by fre-hu** [comment]
As I'm thinking, Span (or Slice) is very similar to the Rust slice type, and it can represent a part of the container but also the full container. For example with vec.iter() you don't get an iterator over a vector but an iterator over a slice, since vec will first dereference to a slice.

It does not matter how Span is represented internally, and what is important is the interface to the user. Now &Span is a thin pointer, but if/when custom DST is possible I would like to represent it with a wide pointer to the elements and to the mapping type. This is better for the compiler since direct references can have noalias annotations which should help optimizations.

Thanks for the feedback on Tensor vs Grid. I see what you mean about using Tensor for one type when other types are also tensors, but I think it is difficult to avoid. There is the same issue with normal arrays and Vec, that you should use slices in interfaces even though they are arrays/vectors. To me it is all just multidimensional arrays, and I want to find names that are reasonably correct and fit together.

Regarding array references, yes I think it would be better to use ArraySlice instead of ArrayRef. The reason is that &ArrayRef looks like a double reference, and for mutable references it is unclear if they should be called &mut ArrayRef or &mut ArrayMut. But otherwise the proposal is good.

**Comment by fre-hu** [comment]
Yes and no. If you create a Span reference from a Grid, it will point to the RawSpan that is embedded in the grid. So if you copy the reference around or dereference the grid several times they will be identical. But you can also create a view to the same array, so that you get a View or ViewMut instance that contains a new RawSpan internally and can then be dereferenced.

So the difference compared to normal slices is that Span needs an array instance to point to, and not just the array elements. This can only be avoided with custom DSTs that are larger than two words. But otherwise the important function of Span is that it is the type that all arrays can dereference to, and can be used for example in function arguments.

For iteration, the shape and strides are stored in the mapping type in each array instance. If the iteration is over several arrays, they will each have a mapping type (since strides might be different per array) and the arrays are stored recursively in Zip structures. 

When iterating over Span references, they must first be converted to array views that contain a RawSpan and lifetime. This is similar to when iterating over normal slices, since they must first be converted to Iter or IterMut.
